In [1]:
# Package import
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Load dataframe
df = pd.read_csv(r"/content/drive/MyDrive/OTO_DOM_REGRESSION/data_scraping.csv", sep=';')

In [4]:
df.head()

,Tytul,Cena,Lokalizacja,URL,Powierzchnia,Forma własności,Liczba pokoi,Stan wykończenia,Piętro,Balkon / ogród / taras,...,Dostępne od,Rok budowy,Rodzaj zabudowy,Okna,Winda,Media,Zabezpieczenia,Wyposażenie,Informacje dodatkowe,Materiał budynku
0,Apartament na Mokotowie,1900000,"Warszawa, Mokotów, ul. Cybernetyki",https://www.otodom.pl/pl/oferta/apartament-na-...,100 m²,pełna własność,4,do zamieszkania,2/6,balkon,...,brak informacji,brak informacji,apartamentowiec,aluminiowe,tak,brak informacji,"drzwi / okna antywłamaniowe, teren zamknięty, ...","zmywarka, lodówka, meble, piekarnik, kuchenka,...",brak informacji,cegła
1,"Konstancin-Jeziorna, dwupokojowe, BEZPOŚREDNIO",435000,"ul. Wilanowska 12, Osiedle Grapa, Konstancin-J...",https://www.otodom.pl/pl/oferta/konstancin-jez...,46 m²,pełna własność,2,do remontu,2/3,zapytaj,...,brak informacji,1950,kamienica,plastikowe,nie,"telewizja kablowa, internet, telefon","drzwi / okna antywłamaniowe, domofon / wideofon",brak informacji,"piwnica, oddzielna kuchnia",cegła
2,Sprzedam 2 pokojowe mieszkanie 38m2 bezpośrednio!,531962,"Warszawa, Wola, ul. Pawia 32",https://www.otodom.pl/pl/oferta/sprzedam-2-pok...,38 m²,pełna własność,2,do zamieszkania,3/3,balkon,...,brak informacji,brak informacji,blok,plastikowe,nie,"telewizja kablowa, internet",domofon / wideofon,"zmywarka, lodówka, meble, piekarnik, kuchenka,...","piwnica, oddzielna kuchnia",cegła
3,2 pokoje w cudownej lokalizacji,429000,"Warszawa, Bemowo, ul. Mieczysława Wolfkego",https://www.otodom.pl/pl/oferta/2-pokoje-w-cud...,36 m²,spółdzielcze wł. z KW,2,do zamieszkania,8/10,balkon,...,brak informacji,1980,blok,plastikowe,tak,"telewizja kablowa, internet",domofon / wideofon,"lodówka, meble, piekarnik, kuchenka, pralka","piwnica, oddzielna kuchnia",wielka płyta
4,"Bezpośrednio 37. 24m2,Metro Wawrzyszew ,2 pokoje",514000,"Warszawa, Bielany, ul. Przy Agorze",https://www.otodom.pl/pl/oferta/bezposrednio-3...,"37,24 m²",pełna własność,2,do zamieszkania,4/10,zapytaj,...,brak informacji,1968,blok,plastikowe,tak,"telewizja kablowa, internet","domofon / wideofon, monitoring / ochrona",brak informacji,brak informacji,wielka płyta

In [5]:
df.columns

Index(['Tytul', 'Cena', 'Lokalizacja', 'URL', 'Powierzchnia',
       'Forma własności', 'Liczba pokoi', 'Stan wykończenia', 'Piętro',
       'Balkon / ogród / taras', 'Czynsz', 'Miejsce parkingowe',
       'Obsługa zdalna', 'Ogrzewanie', 'Rynek', 'Typ ogłoszeniodawcy',
       'Dostępne od', 'Rok budowy', 'Rodzaj zabudowy', 'Okna', 'Winda',
       'Media', 'Zabezpieczenia', 'Wyposażenie', 'Informacje dodatkowe',
       'Materiał budynku'],
      dtype='object')

In [6]:
df.describe()

,Tytul,Cena,Lokalizacja,URL,Powierzchnia,Forma własności,Liczba pokoi,Stan wykończenia,Piętro,Balkon / ogród / taras,...,Dostępne od,Rok budowy,Rodzaj zabudowy,Okna,Winda,Media,Zabezpieczenia,Wyposażenie,Informacje dodatkowe,Materiał budynku
count,24180,24180,24180,24180,24180,24180,24180,24180,24180,24180,...,18897,18897,18897,18897,18897,18897,18897,18897,18897,18897
unique,22428,4881,4820,24131,4988,5,10,4,269,9,...,408,147,8,4,2,9,52,92,16,11
top,Apartament Z Ogrodem,Zapytaj o ce,"Warszawa, Białołęka",https://www.otodom.pl/pl/oferta/centrum-biznes...,48 m²,pełna własność,3,zapytaj,1,balkon,...,brak informacji,2022,blok,plastikowe,tak,brak informacji,brak informacji,brak informacji,brak informacji,brak informacji
freq,38,5208,1087,2,289,11343,9137,11035,1450,13454,...,16241,2801,8665,9573,11140,9915,8646,13632,9968,8871

In [7]:
# Remove adds with no price
df_clear = df[df['Cena'] != 'Zapytaj o ce']

In [8]:
# Tytuł:
df_clear['Tytul']

0                                  Apartament na Mokotowie
1           Konstancin-Jeziorna, dwupokojowe, BEZPOŚREDNIO
2        Sprzedam 2 pokojowe mieszkanie 38m2 bezpośrednio!
3                          2 pokoje w cudownej lokalizacji
4         Bezpośrednio 37. 24m2,Metro Wawrzyszew ,2 pokoje
                               ...
24175    Dwupoziomowe PARTERiPODDASZE 2 ŁAZIENKI 2msc p...
24176    Dwupoziomowe PARTERiPODDASZE 2 ŁAZIENKI 2msc p...
24177    DWAPOZIOMY mieszkania bezczynszowe WOLA MROKOWSKA
24178        Dwa poziomy Mieszkania ogródek WOLA MROKOWSKA
24179    LOKALE dwupoziomowe 2 msc.postojowe 5 pokoi WO...
Name: Tytul, Length: 18972, dtype: object

In [9]:
# Add title string length and remove title
df_clear['Title_len'] = df_clear['Tytul'].apply(lambda x: len(x))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [10]:
df_clear = df_clear.drop(columns=['Tytul'])

In [11]:
# Cena
df_clear['Cena'].value_counts()

599000       183
550000       181
499000       178
699000       173
650000       161
            ...
843370         1
600861,90      1
814900         1
988000         1
1479400        1
Name: Cena, Length: 4880, dtype: int64

In [12]:
# Convert price to float
df_clear['Cena'] = df_clear['Cena'].apply(lambda x: float(x.replace(',', '.')))

In [13]:
df_clear['Cena']

0        1900000.0
1         435000.0
2         531962.0
3         429000.0
4         514000.0
           ...
24175     429000.0
24176     429000.0
24177     419000.0
24178     419000.0
24179     419000.0
Name: Cena, Length: 18972, dtype: float64

In [15]:
# Lokalizacja
df['Lokalizacja'].value_counts()

Warszawa, Białołęka                                                 1087
Warszawa, Mokotów                                                    925
Warszawa, mazowieckie                                                860
Warszawa, Wola                                                       763
Warszawa, Ursus                                                      722
                                                                    ...
ul. Żwirki i Wigury, Grodzisk Mazowiecki, grodziski, mazowieckie       1
Warszawa, Ursynów, ul. Kabacki Dukt                                    1
Warszawa, Ochota, Bielska                                              1
Warszawa, Śródmieście, ul. gen. Władysława Andersa 26                  1
ul. Postępu, Wola Mrokowska, piaseczyński, mazowieckie                 1
Name: Lokalizacja, Length: 4820, dtype: int64

In [16]:
# Usuwamy kolumnę URL
df_clear = df_clear.drop(columns=['URL'])

In [17]:
# Powierzchnia
df_clear['Powierzchnia'] = df_clear['Powierzchnia'].apply(lambda x: float(x.split(" ")[0].replace('\xa0', '').replace(',', '.')))

In [18]:
df_clear['Powierzchnia'].sort_values()

14894        6.00
3978        12.00
17898       14.60
2333        14.75
1513        15.00
           ...
8856       530.00
23009      560.00
17562      560.00
9908      4136.00
7671     11525.00
Name: Powierzchnia, Length: 18972, dtype: float64

In [19]:
df_clear = df_clear[df_clear['Powierzchnia'] < 300]

In [20]:
# Forma własności
df_clear['Forma własności'].value_counts()

pełna własność               11020
zapytaj                       5599
spółdzielcze własnościowe     1335
spółdzielcze wł. z KW          929
udział                          30
Name: Forma własności, dtype: int64

In [21]:
# zapytaj -> pełna własność
df_clear['Forma własności'] = df_clear['Forma własności'].replace('zapytaj', 'pełna własność')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [22]:
df_clear['Forma własności'].value_counts()

pełna własność               16619
spółdzielcze własnościowe     1335
spółdzielcze wł. z KW          929
udział                          30
Name: Forma własności, dtype: int64

In [23]:
# Liczba pokoi
df_clear['Liczba pokoi'].value_counts()

3                7065
2                6522
4                2641
1                1710
5                 730
6                 184
7                  47
8                   8
więcej niż 10       4
9                   2
Name: Liczba pokoi, dtype: int64

In [24]:
# Usuwamy rekordy z "więcej niż 10"
df_clear = df_clear[df_clear['Liczba pokoi'] != 'więcej niż 10']

In [25]:
df_clear.value_counts()

Cena        Lokalizacja                                              Powierzchnia  Forma własności  Liczba pokoi  Stan wykończenia  Piętro    Balkon / ogród / taras  Czynsz   Miejsce parkingowe        Obsługa zdalna  Ogrzewanie  Rynek      Typ ogłoszeniodawcy   Dostępne od      Rok budowy  Rodzaj zabudowy   Okna             Winda  Media                                 Zabezpieczenia                                                                                           Wyposażenie                                            Informacje dodatkowe  Materiał budynku  Title_len
690000.0    ul. Fryderyka Chopina, Marki, wołomiński, mazowieckie    90.51         pełna własność   4             do wykończenia    zapytaj   ogródek                 zapytaj  garaż/miejsce parkingowe  zapytaj         gazowe      pierwotny  deweloper             brak informacji  2021        szeregowiec       plastikowe       nie    telewizja kablowa, internet, telefon  system alarmowy, drzwi / okna antywłamaniowe, teren zamknięty, domofon / wideofon                        brak informacji                                        dwupoziomowe          cegła             50           20
577000.0    al. Wojska Polskiego, Piastów, pruszkowski, mazowieckie  71.32         pełna własność   2             do wykończenia    4/4       balkon                  zapytaj  garaż/miejsce parkingowe  zapytaj         miejskie    pierwotny  deweloper             brak informacji  2022        blok              plastikowe       tak    telewizja kablowa, internet           domofon / wideofon, monitoring / ochrona                                                                 brak informacji                                        dwupoziomowe          cegła             29           16
739000.0    al. Wojska Polskiego, Piastów, pruszkowski, mazowieckie  94.69         pełna własność   3             do wykończenia    4/4       balkon, taras           zapytaj  garaż/miejsce parkingowe  zapytaj         miejskie    pierwotny  deweloper             brak informacji  2022        blok              plastikowe       tak    telewizja kablowa, internet           domofon / wideofon, monitoring / ochrona                                                                 brak informacji                                        dwupoziomowe          cegła             29           14
699000.0    al. Wojska Polskiego, Piastów, pruszkowski, mazowieckie  89.44         pełna własność   3             do wykończenia    4/4       balkon                  zapytaj  garaż/miejsce parkingowe  zapytaj         miejskie    pierwotny  deweloper             brak informacji  2022        blok              plastikowe       tak    telewizja kablowa, internet           domofon / wideofon, monitoring / ochrona                                                                 brak informacji                                        dwupoziomowe          cegła             31           13
499900.0    Zamienie, piaseczyński, mazowieckie                      63.90         pełna własność   3             do wykończenia    parter/1  zapytaj                 zapytaj  garaż/miejsce parkingowe  zapytaj         gazowe      pierwotny  biuro nieruchomości   brak informacji  2022        dom wolnostojący  drewniane        nie    internet                              brak informacji                                                                                          brak informacji                                        brak informacji       cegła             20           11
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ..
550000.0    Warszawa, Białołęka, Płużnicka                           46.00         pełna własność   2             do zamieszkania   4/6       balkon                  500 zł   garaż/miejsce parkingowe  zapytaj         miejskie    wtórny     biuro nieruchomości   brak informacji  2021        blok              plastikowe       tak    telewizja kablowa, internet           domofon / wideofon, monitoring / ochrona                                                                 meble                                                  pom. użytkowe         inne              24            1
            Warszawa, Białołęka, Tarchomin                           41.00         pełna własność   2             zapytaj           parter/3  balkon, ogródek         zapytaj  garaż/miejsce parkingowe  zapytaj         zapytaj     wtórny     biuro nieruchomości   brak informacji  2014        blok              brak informacji  tak    brak informacji                       brak informacji                                                                                          brak informacji                                        oddzielna kuchnia     silikat           45            1
            Warszawa, Białołęka, Tarchomin, Myśliborska              47.30         pełna własność   3             do zamieszkania   2/3       zapytaj                 400 zł   zapytaj                   zapytaj         miejskie    wtórny     biuro nieruchomości   brak informacji  2003        blok              brak informacji  nie    brak informacji                       brak informacji                                                                                          brak informacji                                        brak informacji       cegła             42            1
            Warszawa, Białołęka, ul. Skarbka z Gór                   63.10         pełna własność   3             zapytaj           1/3       balkon                  750 zł   garaż/miejsce parkingowe  zapytaj         gazowe      wtórny     prywatny              brak informacji  2004        blok              brak informacji  nie    telewizja kablowa, internet           teren zamknięty, domofon / wideofon, monitoring / ochrona                                                zmywarka, lodówka, meble, piekarnik, kuchenka, pralka  oddzielna kuchnia     pustak            32            1
13000000.0  Warszawa, Śródmieście, Parkowa                           270.00        pełna własność   5             do zamieszkania   parter/5  ogródek                 zapytaj  garaż/miejsce parkingowe  zapytaj         miejskie    wtórny     biuro nieruchomości   brak informacji  2010        apartamentowiec   drewniane        tak    telewizja kablowa, internet, telefon  system alarmowy, drzwi / okna antywłamaniowe, teren zamknięty, domofon / wideofon, monitoring / ochrona  meble                                                  pom. użytkowe         brak informacji   42            1
Length: 16265, dtype: int64

In [26]:
df_clear['Liczba pokoi'] = df_clear['Liczba pokoi'].apply(lambda x: float(x))

In [27]:
# Stan wykończenia
df_clear['Stan wykończenia'].value_counts()

do zamieszkania    7225
zapytaj            6429
do wykończenia     3864
do remontu         1391
Name: Stan wykończenia, dtype: int64

In [28]:
df_clear['Stan wykończenia'] = df_clear['Stan wykończenia'].replace('zapytaj', 'brak informacji')

In [29]:
df_clear['Stan wykończenia'].value_counts()

do zamieszkania    7225
brak informacji    6429
do wykończenia     3864
do remontu         1391
Name: Stan wykończenia, dtype: int64

In [30]:
# Piętro
df_clear['Piętro'].value_counts()

4/4           956
1/3           825
3/3           792
2/3           787
3/4           787
             ...
10/25           1
1/18            1
9/22            1
suterena/4      1
7/21            1
Name: Piętro, Length: 266, dtype: int64

In [31]:
sum(df_clear['Piętro']=='zapytaj')

360

In [32]:
df_clear = df_clear[df_clear['Piętro'] != 'zapytaj']

In [33]:
sum(df_clear['Piętro']=='zapytaj')

0

In [34]:
df_clear[df_clear['Piętro'] == '> 10']

,Cena,Lokalizacja,Powierzchnia,Forma własności,Liczba pokoi,Stan wykończenia,Piętro,Balkon / ogród / taras,Czynsz,Miejsce parkingowe,...,Rok budowy,Rodzaj zabudowy,Okna,Winda,Media,Zabezpieczenia,Wyposażenie,Informacje dodatkowe,Materiał budynku,Title_len
327,1950000.00,"Warszawa, Targówek, ul. Turmoncka",207.00,pełna własność,4.0,do zamieszkania,> 10,taras,2 000 zł,garaż/miejsce parkingowe,...,2005,apartamentowiec,aluminiowe,tak,"telewizja kablowa, internet, telefon","system alarmowy, drzwi / okna antywłamaniowe, ...","zmywarka, lodówka, meble, kuchenka",dwupoziomowe,beton,50
792,807469.00,"Warszawa, Wola",45.11,pełna własność,2.0,do wykończenia,> 10,balkon,zapytaj,garaż/miejsce parkingowe,...,brak informacji,apartamentowiec,brak informacji,tak,brak informacji,"teren zamknięty, monitoring / ochrona",brak informacji,brak informacji,brak informacji,37
816,857675.00,"Warszawa, Wola",50.75,pełna własność,3.0,do wykończenia,> 10,balkon,zapytaj,garaż/miejsce parkingowe,...,brak informacji,apartamentowiec,brak informacji,tak,brak informacji,"teren zamknięty, monitoring / ochrona",brak informacji,brak informacji,brak informacji,37
1579,1446000.00,"Warszawa, Wola",54.30,pełna własność,3.0,brak informacji,> 10,taras,zapytaj,garaż/miejsce parkingowe,...,2024,brak informacji,brak informacji,nie,brak informacji,brak informacji,brak informacji,brak informacji,brak informacji,48
2485,695000.00,"Warszawa, Ursynów, Stokłosy",45.88,pełna własność,2.0,do zamieszkania,> 10,balkon,zapytaj,garaż/miejsce parkingowe,...,2007,apartamentowiec,plastikowe,tak,brak informacji,brak informacji,"lodówka, meble, piekarnik, kuchenka, pralka",oddzielna kuchnia,brak informacji,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22818,657251.00,"Warszawa, Wola, ul. Towarowa",35.18,pełna własność,1.0,do wykończenia,> 10,zapytaj,zapytaj,garaż/miejsce parkingowe,...,2024,apartamentowiec,brak informacji,tak,internet,brak informacji,brak informacji,brak informacji,brak informacji,37
22839,2039785.37,"Warszawa, Wola, ul. Towarowa",77.29,pełna własność,4.0,do wykończenia,> 10,zapytaj,zapytaj,garaż/miejsce parkingowe,...,2024,apartamentowiec,brak informacji,tak,"telewizja kablowa, internet",brak informacji,brak informacji,brak informacji,brak informacji,37
22892,679928.00,"Warszawa, Wola",35.00,pełna własność,1.0,brak informacji,> 10,balkon,zapytaj,garaż/miejsce parkingowe,...,2024,apartamentowiec,aluminiowe,nie,internet,brak informacji,brak informacji,brak informacji,cegła,49
23420,1090000.00,"Warszawa, Śródmieście",54.00,pełna własność,2.0,do zamieszkania,> 10,zapytaj,zapytaj,garaż/miejsce parkingowe,...,2001,apartamentowiec,plastikowe,tak,brak informacji,brak informacji,"zmywarka, lodówka, meble, piekarnik, kuchenka,...",oddzielna kuchnia,brak informacji,41
23544,2100000.00,"Warszawa, Śródmieście",53.00,pełna własność,2.0,brak informacji,> 10,zapytaj,zapytaj,zapytaj,...,brak informacji,brak informacji,brak informacji,nie,brak informacji,brak informacji,brak informacji,brak informacji,brak informacji,33

In [35]:
# Fill missing data with random numbers 
for i in df_clear.index:
    if((df_clear.loc[i, ['Piętro']] == '> 10').bool()):
        df_clear.loc[i, ['Piętro']] = str(np.random.randint(11, 16))

In [36]:
df_clear[df_clear['Piętro'] == '> 10']

Empty DataFrame
Columns: [Cena, Lokalizacja, Powierzchnia, Forma własności, Liczba pokoi, Stan wykończenia, Piętro, Balkon / ogród / taras, Czynsz, Miejsce parkingowe, Obsługa zdalna, Ogrzewanie, Rynek, Typ ogłoszeniodawcy, Dostępne od, Rok budowy, Rodzaj zabudowy, Okna, Winda, Media, Zabezpieczenia, Wyposażenie, Informacje dodatkowe, Materiał budynku, Title_len]
Index: []

[0 rows x 25 columns]

In [37]:
def calc_floor(row):
    if('/' in row):
        if('> 10' in row.split('/')[0]):
            #print(row)
            try:
                return np.random.randint(11, (float(row.split('/')[1]) + 2))
            except:
                return row.split('/')[1]
        else:
            return row.split('/')[0]
    elif('> 10' in row):
        return np.random.randint(11, 16)
    else:
        return row

In [38]:
# numer_pietra
df_clear['numer_pietra'] = df_clear['Piętro'].apply(lambda x: calc_floor(x))

In [39]:
# liczba_pieter
def calc_floorNo(row):
    if('/' in row):
        if('> 10' in row.split('/')[1]):
            return np.random.randint(float(row.split('/')[0]), 16)
        else:
            return row.split('/')[1]
    else:
        return row

In [40]:
# liczba_pieter
df_clear['liczba_pieter'] = df_clear['Piętro'].apply(lambda x: calc_floorNo(x))

In [41]:
# Parter

In [42]:
df_clear['liczba_pieter'].value_counts()

4         3785
3         3325
2         2226
10        1470
5         1372
6         1136
1         1023
8          869
7          840
parter     455
11         401
12         329
9          315
15         234
29         101
13          99
14          90
16          73
27          59
22          51
26          48
24          46
17          40
21          26
23          26
20          22
28          15
18          14
44          12
30          12
25          11
52          11
19           9
54           2
37           1
35           1
Name: liczba_pieter, dtype: int64

In [43]:
df_clear['liczba_pieter'] = df_clear['liczba_pieter'].replace('parter', '0')
df_clear['numer_pietra'] = df_clear['numer_pietra'].replace('parter', '0')

In [44]:
df_clear[df_clear['numer_pietra'] == 'poddasze']

,Cena,Lokalizacja,Powierzchnia,Forma własności,Liczba pokoi,Stan wykończenia,Piętro,Balkon / ogród / taras,Czynsz,Miejsce parkingowe,...,Okna,Winda,Media,Zabezpieczenia,Wyposażenie,Informacje dodatkowe,Materiał budynku,Title_len,numer_pietra,liczba_pieter
1786,221000.0,"Pruszków, Żbików, ul. Górna",31.55,pełna własność,2.0,do remontu,poddasze/2,zapytaj,320 zł,zapytaj,...,plastikowe,nie,"telewizja kablowa, internet","drzwi / okna antywłamaniowe, teren zamknięty, ...",brak informacji,brak informacji,cegła,48,poddasze,2
1795,240000.0,"Pruszków, Żbików, ul. Górna",34.08,pełna własność,2.0,do remontu,poddasze/2,zapytaj,400 zł,zapytaj,...,plastikowe,nie,"telewizja kablowa, internet","drzwi / okna antywłamaniowe, teren zamknięty, ...",brak informacji,oddzielna kuchnia,cegła,50,poddasze,2
23199,805524.5,"Pruszków, Żbików, ul. 3 Maja",96.47,pełna własność,4.0,brak informacji,poddasze/3,balkon,zapytaj,garaż/miejsce parkingowe,...,brak informacji,nie,brak informacji,brak informacji,brak informacji,brak informacji,brak informacji,49,poddasze,3
23203,673466.0,"Pruszków, Żbików, ul. 3 Maja",82.13,pełna własność,3.0,brak informacji,poddasze/3,balkon,zapytaj,garaż/miejsce parkingowe,...,brak informacji,nie,brak informacji,brak informacji,brak informacji,brak informacji,brak informacji,44,poddasze,3
23217,783838.0,"Pruszków, Żbików, ul. 3 Maja",95.59,pełna własność,3.0,brak informacji,poddasze/3,balkon,zapytaj,garaż/miejsce parkingowe,...,brak informacji,nie,brak informacji,brak informacji,brak informacji,brak informacji,brak informacji,50,poddasze,3
23220,346580.0,"Pruszków, Żbików, ul. 3 Maja",40.30,pełna własność,2.0,brak informacji,poddasze/3,balkon,zapytaj,garaż/miejsce parkingowe,...,brak informacji,nie,brak informacji,brak informacji,brak informacji,brak informacji,brak informacji,50,poddasze,3

In [45]:
# Fill 'poddasze' data with number of floors 
for i in df_clear.index:
    if((df_clear.loc[i, ['numer_pietra']] == 'poddasze').bool()):
        df_clear.loc[i, ['numer_pietra']] = str(df_clear.loc[i, ['liczba_pieter']][0])

In [46]:
# Suterena

In [47]:
df_clear = df_clear[df_clear['numer_pietra'] != 'suterena']

In [48]:
# Convert new columns to float

In [49]:
df_clear['numer_pietra'] = df_clear['numer_pietra'].apply(lambda x: float(x))

In [50]:
df_clear['liczba_pieter'] = df_clear['liczba_pieter'].apply(lambda x: float(x))

In [51]:
df_clear.head()

,Cena,Lokalizacja,Powierzchnia,Forma własności,Liczba pokoi,Stan wykończenia,Piętro,Balkon / ogród / taras,Czynsz,Miejsce parkingowe,...,Okna,Winda,Media,Zabezpieczenia,Wyposażenie,Informacje dodatkowe,Materiał budynku,Title_len,numer_pietra,liczba_pieter
0,1900000.0,"Warszawa, Mokotów, ul. Cybernetyki",100.00,pełna własność,4.0,do zamieszkania,2/6,balkon,zapytaj,garaż/miejsce parkingowe,...,aluminiowe,tak,brak informacji,"drzwi / okna antywłamaniowe, teren zamknięty, ...","zmywarka, lodówka, meble, piekarnik, kuchenka,...",brak informacji,cegła,23,2.0,6.0
1,435000.0,"ul. Wilanowska 12, Osiedle Grapa, Konstancin-J...",46.00,pełna własność,2.0,do remontu,2/3,zapytaj,200 zł,zapytaj,...,plastikowe,nie,"telewizja kablowa, internet, telefon","drzwi / okna antywłamaniowe, domofon / wideofon",brak informacji,"piwnica, oddzielna kuchnia",cegła,46,2.0,3.0
2,531962.0,"Warszawa, Wola, ul. Pawia 32",38.00,pełna własność,2.0,do zamieszkania,3/3,balkon,450 zł,garaż/miejsce parkingowe,...,plastikowe,nie,"telewizja kablowa, internet",domofon / wideofon,"zmywarka, lodówka, meble, piekarnik, kuchenka,...","piwnica, oddzielna kuchnia",cegła,49,3.0,3.0
3,429000.0,"Warszawa, Bemowo, ul. Mieczysława Wolfkego",36.00,spółdzielcze wł. z KW,2.0,do zamieszkania,8/10,balkon,500 zł,zapytaj,...,plastikowe,tak,"telewizja kablowa, internet",domofon / wideofon,"lodówka, meble, piekarnik, kuchenka, pralka","piwnica, oddzielna kuchnia",wielka płyta,31,8.0,10.0
4,514000.0,"Warszawa, Bielany, ul. Przy Agorze",37.24,pełna własność,2.0,do zamieszkania,4/10,zapytaj,370 zł,zapytaj,...,plastikowe,tak,"telewizja kablowa, internet","domofon / wideofon, monitoring / ochrona",brak informacji,brak informacji,wielka płyta,48,4.0,10.0

In [52]:
# Remove "Pietro" column - we do not have to use it again
df_clear = df_clear.drop(columns=['Piętro'])

In [53]:
# Balkon / ogród / taras
df_clear['Balkon / ogród / taras'].value_counts()

balkon                    10172
zapytaj                    5344
balkon, taras               743
ogródek                     736
taras                       551
balkon, ogródek             363
ogródek, taras              343
balkon, ogródek, taras      292
taras, balkon                 3
Name: Balkon / ogród / taras, dtype: int64

In [54]:
df_clear['Balkon / ogród / taras'] = df_clear['Balkon / ogród / taras'].replace('zapytaj', 'brak informacji')

In [55]:
# Czynsz
df_clear['Czynsz'].value_counts()

zapytaj      10298
500 zł         607
600 zł         535
400 zł         391
700 zł         390
             ...
903,38 zł        1
2 599 zł         1
676 zł           1
705,84 zł        1
262 zł           1
Name: Czynsz, Length: 729, dtype: int64

In [56]:
df_clear = df_clear.drop(columns=['Czynsz'])

In [57]:
# Miejsce parkingowe
df_clear['Miejsce parkingowe'].value_counts()

garaż/miejsce parkingowe    10416
zapytaj                      8131
Name: Miejsce parkingowe, dtype: int64

In [58]:
df_clear['Miejsce parkingowe'] = df_clear['Miejsce parkingowe'].replace('zapytaj', 'brak')

In [59]:
# Check number of missing (nan) data 
df_clear.isna().sum()

Cena                         0
Lokalizacja                  0
Powierzchnia                 0
Forma własności              0
Liczba pokoi                 0
Stan wykończenia             0
Balkon / ogród / taras       0
Miejsce parkingowe           0
Obsługa zdalna            2130
Ogrzewanie                   0
Rynek                     1079
Typ ogłoszeniodawcy       1079
Dostępne od               1079
Rok budowy                1079
Rodzaj zabudowy           1079
Okna                      1079
Winda                     1079
Media                     1079
Zabezpieczenia            1079
Wyposażenie               1079
Informacje dodatkowe      1079
Materiał budynku          1079
Title_len                    0
numer_pietra                 0
liczba_pieter                0
dtype: int64

In [60]:
# Obsługa zdalna
df_clear['Obsługa zdalna'].value_counts()

zapytaj    14797
tak         1620
Name: Obsługa zdalna, dtype: int64

In [61]:
df_clear = df_clear.drop(columns=['Obsługa zdalna'])

In [62]:
# Ogrzewanie
df_clear['Ogrzewanie'].value_counts()

miejskie       10088
zapytaj         6214
gazowe          1384
inne             527
kotłownia        279
elektryczne       55
Name: Ogrzewanie, dtype: int64

In [63]:
df_clear['Ogrzewanie'] = df_clear['Ogrzewanie'].replace('zapytaj', 'brak informacji')

In [64]:
# Rynek
df_clear['Rynek'].value_counts()

wtórny       11916
pierwotny     5552
Name: Rynek, dtype: int64

In [65]:
df_clear['Rynek'].isna().sum()

1079

In [66]:
# Let's assume that nan values are 'wtórny'
df_clear['Rynek'] = df_clear['Rynek'].fillna(value=0)

In [67]:
df_clear['Rynek'].isna().sum()

0

In [68]:
def market_swap(row):
    if(row == 'wtórny' or row == 0):
        return 0
    else:
        return 1

In [69]:
df_clear['Rynek'] = df_clear['Rynek'].apply(market_swap)

In [70]:
df_clear['Rynek'].value_counts()

0    12995
1     5552
Name: Rynek, dtype: int64

In [71]:
# Typ ogłoszeniodawcy

In [72]:
df_clear['Typ ogłoszeniodawcy'].value_counts()

biuro nieruchomości     14233
prywatny                 2075
deweloper                1160
Name: Typ ogłoszeniodawcy, dtype: int64

In [73]:
df_clear['Typ ogłoszeniodawcy'].isna().sum()

1079

In [74]:
df_clear = df_clear.drop(columns=['Typ ogłoszeniodawcy'])

In [75]:
# Dostępne od
df_clear['Dostępne od'].value_counts()

brak informacji    14845
2022-03-07           311
2022-09-07           103
2022-03-01            97
2022-02-01            66
                   ...
2021-02-08             1
2023-07-14             1
2023-07-07             1
2022-07-18             1
2010-09-24             1
Name: Dostępne od, Length: 403, dtype: int64

In [76]:
df_clear = df_clear.drop(columns=['Dostępne od'])

In [77]:
# Rok budowy
df_clear['Rok budowy'].value_counts()

2022               2280
brak informacji    1938
2021               1531
2023                948
2020                420
                   ...
570                   1
1833                  1
195                   1
1896                  1
1828                  1
Name: Rok budowy, Length: 146, dtype: int64

In [78]:
df_clear = df_clear.drop(columns=['Rok budowy'])

In [79]:
# Rodzaj zabudowy
df_clear['Rodzaj zabudowy'].value_counts()

blok                8305
apartamentowiec     4003
brak informacji     3252
kamienica           1287
szeregowiec          392
dom wolnostojący     224
plomba                 3
loft                   2
Name: Rodzaj zabudowy, dtype: int64

In [80]:
df_clear['Rodzaj zabudowy'].isna().sum()

1079

In [81]:
df_clear['Rodzaj zabudowy'] = df_clear['Rodzaj zabudowy'].fillna(value = 'brak informacji')

In [82]:
# Remove rows with values plomba, loft (only few records)
df_clear = df_clear[df_clear['Rodzaj zabudowy'] != 'plomba']

In [83]:
df_clear = df_clear[df_clear['Rodzaj zabudowy'] != 'loft']

In [84]:
df_clear['Rodzaj zabudowy'].value_counts()

blok                8305
brak informacji     4331
apartamentowiec     4003
kamienica           1287
szeregowiec          392
dom wolnostojący     224
Name: Rodzaj zabudowy, dtype: int64

In [85]:
# No nan values
df_clear['Rodzaj zabudowy'].isna().sum()

0

In [86]:
# Okna
df_clear['Okna'].value_counts()

plastikowe         9186
brak informacji    6412
drewniane          1601
aluminiowe          264
Name: Okna, dtype: int64

In [87]:
df_clear['Okna'].isna().sum()

1079

In [88]:
df_clear['Okna'] = df_clear['Okna'].fillna(value = 'brak informacji')

In [89]:
df_clear['Okna'].value_counts()

plastikowe         9186
brak informacji    7491
drewniane          1601
aluminiowe          264
Name: Okna, dtype: int64

In [90]:
# Winda
df_clear['Winda'].value_counts()

tak    10276
nie     7187
Name: Winda, dtype: int64

In [91]:
df_clear['Winda'].isna().sum()

1079

In [92]:
df_clear['Winda'] = df_clear['Winda'].fillna(value = 'nie')

In [93]:
df_clear['Winda'].value_counts()

tak    10276
nie     8266
Name: Winda, dtype: int64

In [94]:
df_clear['Winda'].isna().sum()

0

In [95]:
# Media
df_clear['Media'].value_counts()

brak informacji                         9329
telewizja kablowa, internet, telefon    3917
telewizja kablowa, internet             2767
internet                                 891
telewizja kablowa                        211
internet, telefon                        172
telewizja kablowa, telefon               111
telefon                                   65
Name: Media, dtype: int64

In [96]:
df_clear = df_clear.drop(columns = ['Media'])

In [97]:
# Zabezpieczenia
df_clear['Zabezpieczenia'].value_counts()

brak informacji                                                                                                                   8045
domofon / wideofon                                                                                                                1555
monitoring / ochrona                                                                                                              1445
drzwi / okna antywłamaniowe, teren zamknięty, domofon / wideofon, monitoring / ochrona                                            1225
drzwi / okna antywłamaniowe, domofon / wideofon                                                                                    856
drzwi / okna antywłamaniowe, domofon / wideofon, monitoring / ochrona                                                              710
teren zamknięty, domofon / wideofon, monitoring / ochrona                                                                          702
domofon / wideofon, monitoring / ochrona                                                                                           673
teren zamknięty, domofon / wideofon                                                                                                541
drzwi / okna antywłamaniowe, teren zamknięty, domofon / wideofon                                                                   366
system alarmowy, drzwi / okna antywłamaniowe, teren zamknięty, domofon / wideofon, monitoring / ochrona                            220
teren zamknięty                                                                                                                    205
system alarmowy, drzwi / okna antywłamaniowe, domofon / wideofon, monitoring / ochrona                                             113
system alarmowy, drzwi / okna antywłamaniowe, teren zamknięty, domofon / wideofon                                                   77
drzwi / okna antywłamaniowe                                                                                                         70
system alarmowy, teren zamknięty, domofon / wideofon                                                                                67
system alarmowy, teren zamknięty, domofon / wideofon, monitoring / ochrona                                                          64
teren zamknięty, monitoring / ochrona                                                                                               60
system alarmowy, drzwi / okna antywłamaniowe, teren zamknięty, domofon / wideofon, monitoring / ochrona, rolety antywłamaniowe      60
system alarmowy, domofon / wideofon, monitoring / ochrona                                                                           48
drzwi / okna antywłamaniowe, teren zamknięty, domofon / wideofon, monitoring / ochrona, rolety antywłamaniowe                       44
drzwi / okna antywłamaniowe, monitoring / ochrona                                                                                   40
system alarmowy, domofon / wideofon                                                                                                 33
drzwi / okna antywłamaniowe, teren zamknięty                                                                                        31
drzwi / okna antywłamaniowe, teren zamknięty, monitoring / ochrona                                                                  23
domofon / wideofon, monitoring / ochrona, rolety antywłamaniowe                                                                     20
drzwi / okna antywłamaniowe, teren zamknięty, domofon / wideofon, rolety antywłamaniowe                                             20
system alarmowy, drzwi / okna antywłamaniowe, domofon / wideofon                                                                    19
drzwi / okna antywłamaniowe, domofon / wideofon, monitoring / ochrona, rolety antywłamaniowe                                        17
teren zamknięty, domofon / wideofon, monitoring / ochrona, rolety antywłamaniowe                                                    13
drzwi / okna antywłamaniowe, domofon / wideofon, rolety antywłamaniowe                                                              12
system alarmowy                                                                                                                     10
system alarmowy, drzwi / okna antywłamaniowe                                                                                        10
domofon / wideofon, rolety antywłamaniowe                                                                                            9
teren zamknięty, domofon / wideofon, rolety antywłamaniowe                                                                           7
system alarmowy, drzwi / okna antywłamaniowe, teren zamknięty, domofon / wideofon, rolety antywłamaniowe                             7
system alarmowy, teren zamknięty                                                                                                     6
system alarmowy, monitoring / ochrona                                                                                                6
system alarmowy, drzwi / okna antywłamaniowe, teren zamknięty, monitoring / ochrona                                                  6
system alarmowy, drzwi / okna antywłamaniowe, domofon / wideofon, monitoring / ochrona, rolety antywłamaniowe                        6
system alarmowy, teren zamknięty, domofon / wideofon, monitoring / ochrona, rolety antywłamaniowe                                    5
teren zamknięty, monitoring / ochrona, rolety antywłamaniowe                                                                         3
system alarmowy, drzwi / okna antywłamaniowe, monitoring / ochrona                                                                   3
system alarmowy, drzwi / okna antywłamaniowe, domofon / wideofon, rolety antywłamaniowe                                              2
system alarmowy, teren zamknięty, monitoring / ochrona                                                                               2
system alarmowy, domofon / wideofon, monitoring / ochrona, rolety antywłamaniowe                                                     1
drzwi / okna antywłamaniowe, monitoring / ochrona, rolety antywłamaniowe                                                             1
drzwi / okna antywłamaniowe, rolety antywłamaniowe                                                                                   1
system alarmowy, drzwi / okna antywłamaniowe, teren zamknięty                                                                        1
system alarmowy, domofon / wideofon, rolety antywłamaniowe                                                                           1
rolety antywłamaniowe                                                                                                                1
system alarmowy, teren zamknięty, domofon / wideofon, rolety antywłamaniowe                                                          1
Name: Zabezpieczenia, dtype: int64

In [98]:
df_clear = df_clear.drop(columns = ['Zabezpieczenia'])

In [99]:
# Wyposażenie 
df_clear['Wyposażenie'].value_counts()

brak informacji                                                     12246
meble                                                                1917
zmywarka, lodówka, meble, piekarnik, kuchenka, pralka                 738
zmywarka, lodówka, meble, piekarnik, kuchenka, telewizor, pralka      684
lodówka, meble, piekarnik, kuchenka, pralka                           299
                                                                    ...
zmywarka, meble, piekarnik, kuchenka, telewizor, pralka                 1
zmywarka, lodówka, kuchenka, telewizor, pralka                          1
lodówka, meble, telewizor, pralka                                       1
telewizor                                                               1
zmywarka, meble                                                         1
Name: Wyposażenie, Length: 92, dtype: int64

In [100]:
df_clear = df_clear.drop(columns = ['Wyposażenie'])

In [101]:
# Info dodatkowe
df_clear['Informacje dodatkowe'].value_counts()

brak informacji                                            8890
piwnica                                                    2717
pom. użytkowe                                              1581
piwnica, oddzielna kuchnia                                 1228
oddzielna kuchnia                                          1138
piwnica, pom. użytkowe                                      725
piwnica, oddzielna kuchnia, pom. użytkowe                   370
dwupoziomowe                                                364
oddzielna kuchnia, pom. użytkowe                            168
dwupoziomowe, pom. użytkowe                                  96
piwnica, dwupoziomowe                                        81
oddzielna kuchnia, dwupoziomowe                              52
piwnica, oddzielna kuchnia, dwupoziomowe, pom. użytkowe      17
oddzielna kuchnia, dwupoziomowe, pom. użytkowe               13
piwnica, dwupoziomowe, pom. użytkowe                         12
piwnica, oddzielna kuchnia, dwupoziomowe                     11
Name: Informacje dodatkowe, dtype: int64

In [102]:
df_clear['Informacje dodatkowe'] = df_clear['Informacje dodatkowe'].fillna(value = 'brak informacji')

In [103]:
df_clear['Informacje dodatkowe'].isna().sum()

0

In [104]:
# Materiał budynku 
df_clear['Materiał budynku'].value_counts()

brak informacji                                                  7739
cegła                                                            5305
inne                                                             1523
wielka płyta                                                     1242
żelbet                                                            493
pustak                                                            471
silikat                                                           365
beton komórkowy                                                   210
beton                                                             108
frontend.ad.table-information-value-building_material-69-wood       5
keramzyt                                                            2
Name: Materiał budynku, dtype: int64

In [105]:
df_clear['Materiał budynku'] = df_clear['Materiał budynku'].fillna(value = 'brak informacji')

In [106]:
df_clear['Materiał budynku'].isna().sum()

0

In [107]:
df_clear = df_clear[df_clear['Materiał budynku'] != 'keramzyt']

In [108]:
df_clear = df_clear[df_clear['Materiał budynku'] != 'frontend.ad.table-information-value-building_material-69-wood']

In [109]:
df_clear['Materiał budynku'].value_counts()

brak informacji    8818
cegła              5305
inne               1523
wielka płyta       1242
żelbet              493
pustak              471
silikat             365
beton komórkowy     210
beton               108
Name: Materiał budynku, dtype: int64

In [110]:
# Change dataframe columns to numeric values

In [111]:
df_clear.columns

Index(['Cena', 'Lokalizacja', 'Powierzchnia', 'Forma własności',
       'Liczba pokoi', 'Stan wykończenia', 'Balkon / ogród / taras',
       'Miejsce parkingowe', 'Ogrzewanie', 'Rynek', 'Rodzaj zabudowy', 'Okna',
       'Winda', 'Informacje dodatkowe', 'Materiał budynku', 'Title_len',
       'numer_pietra', 'liczba_pieter'],
      dtype='object')

In [112]:
df_clear.head()

,Cena,Lokalizacja,Powierzchnia,Forma własności,Liczba pokoi,Stan wykończenia,Balkon / ogród / taras,Miejsce parkingowe,Ogrzewanie,Rynek,Rodzaj zabudowy,Okna,Winda,Informacje dodatkowe,Materiał budynku,Title_len,numer_pietra,liczba_pieter
0,1900000.0,"Warszawa, Mokotów, ul. Cybernetyki",100.00,pełna własność,4.0,do zamieszkania,balkon,garaż/miejsce parkingowe,brak informacji,0,apartamentowiec,aluminiowe,tak,brak informacji,cegła,23,2.0,6.0
1,435000.0,"ul. Wilanowska 12, Osiedle Grapa, Konstancin-J...",46.00,pełna własność,2.0,do remontu,brak informacji,brak,elektryczne,0,kamienica,plastikowe,nie,"piwnica, oddzielna kuchnia",cegła,46,2.0,3.0
2,531962.0,"Warszawa, Wola, ul. Pawia 32",38.00,pełna własność,2.0,do zamieszkania,balkon,garaż/miejsce parkingowe,miejskie,0,blok,plastikowe,nie,"piwnica, oddzielna kuchnia",cegła,49,3.0,3.0
3,429000.0,"Warszawa, Bemowo, ul. Mieczysława Wolfkego",36.00,spółdzielcze wł. z KW,2.0,do zamieszkania,balkon,brak,miejskie,0,blok,plastikowe,tak,"piwnica, oddzielna kuchnia",wielka płyta,31,8.0,10.0
4,514000.0,"Warszawa, Bielany, ul. Przy Agorze",37.24,pełna własność,2.0,do zamieszkania,brak informacji,brak,miejskie,0,blok,plastikowe,tak,brak informacji,wielka płyta,48,4.0,10.0

In [113]:
# Copy dataframe (map visualization)
df_map = df_clear.copy()

In [114]:
# Remove localization column
df_clear = df_clear.drop(columns=['Lokalizacja'])

In [115]:
# Forma własności
df_clear['Forma własności'].value_counts()

pełna własność               16248
spółdzielcze własnościowe     1330
spółdzielcze wł. z KW          927
udział                          30
Name: Forma własności, dtype: int64

In [116]:
df_clear

,Cena,Powierzchnia,Forma własności,Liczba pokoi,Stan wykończenia,Balkon / ogród / taras,Miejsce parkingowe,Ogrzewanie,Rynek,Rodzaj zabudowy,Okna,Winda,Informacje dodatkowe,Materiał budynku,Title_len,numer_pietra,liczba_pieter
0,1900000.0,100.00,pełna własność,4.0,do zamieszkania,balkon,garaż/miejsce parkingowe,brak informacji,0,apartamentowiec,aluminiowe,tak,brak informacji,cegła,23,2.0,6.0
1,435000.0,46.00,pełna własność,2.0,do remontu,brak informacji,brak,elektryczne,0,kamienica,plastikowe,nie,"piwnica, oddzielna kuchnia",cegła,46,2.0,3.0
2,531962.0,38.00,pełna własność,2.0,do zamieszkania,balkon,garaż/miejsce parkingowe,miejskie,0,blok,plastikowe,nie,"piwnica, oddzielna kuchnia",cegła,49,3.0,3.0
3,429000.0,36.00,spółdzielcze wł. z KW,2.0,do zamieszkania,balkon,brak,miejskie,0,blok,plastikowe,tak,"piwnica, oddzielna kuchnia",wielka płyta,31,8.0,10.0
4,514000.0,37.24,pełna własność,2.0,do zamieszkania,brak informacji,brak,miejskie,0,blok,plastikowe,tak,brak informacji,wielka płyta,48,4.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24169,1479400.0,113.80,pełna własność,4.0,do zamieszkania,balkon,garaż/miejsce parkingowe,miejskie,0,blok,brak informacji,tak,"piwnica, oddzielna kuchnia",wielka płyta,31,10.0,10.0
24170,1250000.0,102.00,spółdzielcze wł. z KW,4.0,brak informacji,brak informacji,brak,brak informacji,0,blok,brak informacji,nie,brak informacji,cegła,48,3.0,4.0
24171,419000.0,111.00,pełna własność,5.0,brak informacji,brak informacji,brak,brak informacji,1,szeregowiec,brak informacji,nie,brak informacji,brak informacji,50,1.0,3.0
24173,429000.0,94.79,pełna własność,4.0,brak informacji,brak informacji,brak,brak informacji,1,brak informacji,plastikowe,nie,brak informacji,cegła,50,0.0,0.0
24179,419000.0,111.00,pełna własność,5.0,brak informacji,"balkon, ogródek, taras",garaż/miejsce parkingowe,brak informacji,1,szeregowiec,plastikowe,nie,"dwupoziomowe, pom. użytkowe",cegła,50,1.0,2.0

In [117]:
df_clear = pd.get_dummies(df_clear, columns=['Forma własności'])

In [118]:
df_clear

,Cena,Powierzchnia,Liczba pokoi,Stan wykończenia,Balkon / ogród / taras,Miejsce parkingowe,Ogrzewanie,Rynek,Rodzaj zabudowy,Okna,Winda,Informacje dodatkowe,Materiał budynku,Title_len,numer_pietra,liczba_pieter,Forma własności_pełna własność,Forma własności_spółdzielcze wł. z KW,Forma własności_spółdzielcze własnościowe,Forma własności_udział
0,1900000.0,100.00,4.0,do zamieszkania,balkon,garaż/miejsce parkingowe,brak informacji,0,apartamentowiec,aluminiowe,tak,brak informacji,cegła,23,2.0,6.0,1,0,0,0
1,435000.0,46.00,2.0,do remontu,brak informacji,brak,elektryczne,0,kamienica,plastikowe,nie,"piwnica, oddzielna kuchnia",cegła,46,2.0,3.0,1,0,0,0
2,531962.0,38.00,2.0,do zamieszkania,balkon,garaż/miejsce parkingowe,miejskie,0,blok,plastikowe,nie,"piwnica, oddzielna kuchnia",cegła,49,3.0,3.0,1,0,0,0
3,429000.0,36.00,2.0,do zamieszkania,balkon,brak,miejskie,0,blok,plastikowe,tak,"piwnica, oddzielna kuchnia",wielka płyta,31,8.0,10.0,0,1,0,0
4,514000.0,37.24,2.0,do zamieszkania,brak informacji,brak,miejskie,0,blok,plastikowe,tak,brak informacji,wielka płyta,48,4.0,10.0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24169,1479400.0,113.80,4.0,do zamieszkania,balkon,garaż/miejsce parkingowe,miejskie,0,blok,brak informacji,tak,"piwnica, oddzielna kuchnia",wielka płyta,31,10.0,10.0,1,0,0,0
24170,1250000.0,102.00,4.0,brak informacji,brak informacji,brak,brak informacji,0,blok,brak informacji,nie,brak informacji,cegła,48,3.0,4.0,0,1,0,0
24171,419000.0,111.00,5.0,brak informacji,brak informacji,brak,brak informacji,1,szeregowiec,brak informacji,nie,brak informacji,brak informacji,50,1.0,3.0,1,0,0,0
24173,429000.0,94.79,4.0,brak informacji,brak informacji,brak,brak informacji,1,brak informacji,plastikowe,nie,brak informacji,cegła,50,0.0,0.0,1,0,0,0
24179,419000.0,111.00,5.0,brak informacji,"balkon, ogródek, taras",garaż/miejsce parkingowe,brak informacji,1,szeregowiec,plastikowe,nie,"dwupoziomowe, pom. użytkowe",cegła,50,1.0,2.0,1,0,0,0

In [119]:
# Stan wykonczenia
df_clear['Stan wykończenia'].value_counts()

do zamieszkania    7182
brak informacji    6246
do wykończenia     3727
do remontu         1380
Name: Stan wykończenia, dtype: int64

In [120]:
df_clear = pd.get_dummies(df_clear, columns=['Stan wykończenia'])

In [121]:
df_clear

,Cena,Powierzchnia,Liczba pokoi,Balkon / ogród / taras,Miejsce parkingowe,Ogrzewanie,Rynek,Rodzaj zabudowy,Okna,Winda,...,numer_pietra,liczba_pieter,Forma własności_pełna własność,Forma własności_spółdzielcze wł. z KW,Forma własności_spółdzielcze własnościowe,Forma własności_udział,Stan wykończenia_brak informacji,Stan wykończenia_do remontu,Stan wykończenia_do wykończenia,Stan wykończenia_do zamieszkania
0,1900000.0,100.00,4.0,balkon,garaż/miejsce parkingowe,brak informacji,0,apartamentowiec,aluminiowe,tak,...,2.0,6.0,1,0,0,0,0,0,0,1
1,435000.0,46.00,2.0,brak informacji,brak,elektryczne,0,kamienica,plastikowe,nie,...,2.0,3.0,1,0,0,0,0,1,0,0
2,531962.0,38.00,2.0,balkon,garaż/miejsce parkingowe,miejskie,0,blok,plastikowe,nie,...,3.0,3.0,1,0,0,0,0,0,0,1
3,429000.0,36.00,2.0,balkon,brak,miejskie,0,blok,plastikowe,tak,...,8.0,10.0,0,1,0,0,0,0,0,1
4,514000.0,37.24,2.0,brak informacji,brak,miejskie,0,blok,plastikowe,tak,...,4.0,10.0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24169,1479400.0,113.80,4.0,balkon,garaż/miejsce parkingowe,miejskie,0,blok,brak informacji,tak,...,10.0,10.0,1,0,0,0,0,0,0,1
24170,1250000.0,102.00,4.0,brak informacji,brak,brak informacji,0,blok,brak informacji,nie,...,3.0,4.0,0,1,0,0,1,0,0,0
24171,419000.0,111.00,5.0,brak informacji,brak,brak informacji,1,szeregowiec,brak informacji,nie,...,1.0,3.0,1,0,0,0,1,0,0,0
24173,429000.0,94.79,4.0,brak informacji,brak,brak informacji,1,brak informacji,plastikowe,nie,...,0.0,0.0,1,0,0,0,1,0,0,0
24179,419000.0,111.00,5.0,"balkon, ogródek, taras",garaż/miejsce parkingowe,brak informacji,1,szeregowiec,plastikowe,nie,...,1.0,2.0,1,0,0,0,1,0,0,0

In [122]:
# Balkon / ogród / taras
df_clear['Balkon / ogród / taras'].value_counts()

balkon                    10168
brak informacji            5341
balkon, taras               743
ogródek                     735
taras                       551
balkon, ogródek             362
ogródek, taras              340
balkon, ogródek, taras      292
taras, balkon                 3
Name: Balkon / ogród / taras, dtype: int64

In [123]:
df_clear['Balkon / ogród / taras'].str.get_dummies(sep=', ').add_prefix('balkon_')

       balkon_balkon  balkon_brak informacji  balkon_ogródek  balkon_taras
0                  1                       0               0             0
1                  0                       1               0             0
2                  1                       0               0             0
3                  1                       0               0             0
4                  0                       1               0             0
...              ...                     ...             ...           ...
24169              1                       0               0             0
24170              0                       1               0             0
24171              0                       1               0             0
24173              0                       1               0             0
24179              1                       0               1             1

[18535 rows x 4 columns]

In [124]:
df_clear = pd.concat([df_clear.drop(columns=['Balkon / ogród / taras']), df_clear['Balkon / ogród / taras'].str.get_dummies(sep=', ').add_prefix('balkon_')], 1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  """Entry point for launching an IPython kernel.

In [125]:
df_clear

,Cena,Powierzchnia,Liczba pokoi,Miejsce parkingowe,Ogrzewanie,Rynek,Rodzaj zabudowy,Okna,Winda,Informacje dodatkowe,...,Forma własności_spółdzielcze własnościowe,Forma własności_udział,Stan wykończenia_brak informacji,Stan wykończenia_do remontu,Stan wykończenia_do wykończenia,Stan wykończenia_do zamieszkania,balkon_balkon,balkon_brak informacji,balkon_ogródek,balkon_taras
0,1900000.0,100.00,4.0,garaż/miejsce parkingowe,brak informacji,0,apartamentowiec,aluminiowe,tak,brak informacji,...,0,0,0,0,0,1,1,0,0,0
1,435000.0,46.00,2.0,brak,elektryczne,0,kamienica,plastikowe,nie,"piwnica, oddzielna kuchnia",...,0,0,0,1,0,0,0,1,0,0
2,531962.0,38.00,2.0,garaż/miejsce parkingowe,miejskie,0,blok,plastikowe,nie,"piwnica, oddzielna kuchnia",...,0,0,0,0,0,1,1,0,0,0
3,429000.0,36.00,2.0,brak,miejskie,0,blok,plastikowe,tak,"piwnica, oddzielna kuchnia",...,0,0,0,0,0,1,1,0,0,0
4,514000.0,37.24,2.0,brak,miejskie,0,blok,plastikowe,tak,brak informacji,...,0,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24169,1479400.0,113.80,4.0,garaż/miejsce parkingowe,miejskie,0,blok,brak informacji,tak,"piwnica, oddzielna kuchnia",...,0,0,0,0,0,1,1,0,0,0
24170,1250000.0,102.00,4.0,brak,brak informacji,0,blok,brak informacji,nie,brak informacji,...,0,0,1,0,0,0,0,1,0,0
24171,419000.0,111.00,5.0,brak,brak informacji,1,szeregowiec,brak informacji,nie,brak informacji,...,0,0,1,0,0,0,0,1,0,0
24173,429000.0,94.79,4.0,brak,brak informacji,1,brak informacji,plastikowe,nie,brak informacji,...,0,0,1,0,0,0,0,1,0,0
24179,419000.0,111.00,5.0,garaż/miejsce parkingowe,brak informacji,1,szeregowiec,plastikowe,nie,"dwupoziomowe, pom. użytkowe",...,0,0,1,0,0,0,1,0,1,1

In [126]:
# Miejsce parkingowe, ogrzewanie, rodzaj zabudowy, okna, winda

In [127]:
df_clear['Miejsce parkingowe'].value_counts()

garaż/miejsce parkingowe    10408
brak                         8127
Name: Miejsce parkingowe, dtype: int64

In [128]:
df_clear['Ogrzewanie'].value_counts()

miejskie           10083
brak informacji     6211
gazowe              1383
inne                 526
kotłownia            277
elektryczne           55
Name: Ogrzewanie, dtype: int64

In [129]:
df_clear['Rodzaj zabudowy'].value_counts()

blok                8302
brak informacji     4331
apartamentowiec     4003
kamienica           1285
szeregowiec          390
dom wolnostojący     224
Name: Rodzaj zabudowy, dtype: int64

In [130]:
df_clear['Okna'].value_counts()

plastikowe         9180
brak informacji    7491
drewniane          1600
aluminiowe          264
Name: Okna, dtype: int64

In [131]:
df_clear['Winda'].value_counts()

tak    10274
nie     8261
Name: Winda, dtype: int64

In [132]:
df_clear = pd.get_dummies(df_clear, columns=['Miejsce parkingowe', 'Ogrzewanie', 'Rodzaj zabudowy', 'Okna', 'Winda'])

In [133]:
df_clear

,Cena,Powierzchnia,Liczba pokoi,Rynek,Informacje dodatkowe,Materiał budynku,Title_len,numer_pietra,liczba_pieter,Forma własności_pełna własność,...,Rodzaj zabudowy_brak informacji,Rodzaj zabudowy_dom wolnostojący,Rodzaj zabudowy_kamienica,Rodzaj zabudowy_szeregowiec,Okna_aluminiowe,Okna_brak informacji,Okna_drewniane,Okna_plastikowe,Winda_nie,Winda_tak
0,1900000.0,100.00,4.0,0,brak informacji,cegła,23,2.0,6.0,1,...,0,0,0,0,1,0,0,0,0,1
1,435000.0,46.00,2.0,0,"piwnica, oddzielna kuchnia",cegła,46,2.0,3.0,1,...,0,0,1,0,0,0,0,1,1,0
2,531962.0,38.00,2.0,0,"piwnica, oddzielna kuchnia",cegła,49,3.0,3.0,1,...,0,0,0,0,0,0,0,1,1,0
3,429000.0,36.00,2.0,0,"piwnica, oddzielna kuchnia",wielka płyta,31,8.0,10.0,0,...,0,0,0,0,0,0,0,1,0,1
4,514000.0,37.24,2.0,0,brak informacji,wielka płyta,48,4.0,10.0,1,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24169,1479400.0,113.80,4.0,0,"piwnica, oddzielna kuchnia",wielka płyta,31,10.0,10.0,1,...,0,0,0,0,0,1,0,0,0,1
24170,1250000.0,102.00,4.0,0,brak informacji,cegła,48,3.0,4.0,0,...,0,0,0,0,0,1,0,0,1,0
24171,419000.0,111.00,5.0,1,brak informacji,brak informacji,50,1.0,3.0,1,...,0,0,0,1,0,1,0,0,1,0
24173,429000.0,94.79,4.0,1,brak informacji,cegła,50,0.0,0.0,1,...,1,0,0,0,0,0,0,1,1,0
24179,419000.0,111.00,5.0,1,"dwupoziomowe, pom. użytkowe",cegła,50,1.0,2.0,1,...,0,0,0,1,0,0,0,1,1,0

In [134]:
# Informacje dodatkowe
df_clear['Informacje dodatkowe'].value_counts()

brak informacji                                            9967
piwnica                                                    2717
pom. użytkowe                                              1581
piwnica, oddzielna kuchnia                                 1225
oddzielna kuchnia                                          1137
piwnica, pom. użytkowe                                      725
piwnica, oddzielna kuchnia, pom. użytkowe                   370
dwupoziomowe                                                364
oddzielna kuchnia, pom. użytkowe                            168
dwupoziomowe, pom. użytkowe                                  95
piwnica, dwupoziomowe                                        81
oddzielna kuchnia, dwupoziomowe                              52
piwnica, oddzielna kuchnia, dwupoziomowe, pom. użytkowe      17
oddzielna kuchnia, dwupoziomowe, pom. użytkowe               13
piwnica, dwupoziomowe, pom. użytkowe                         12
piwnica, oddzielna kuchnia, dwupoziomowe                     11
Name: Informacje dodatkowe, dtype: int64

In [135]:
df_clear = pd.concat([df_clear.drop(columns=['Informacje dodatkowe']), df_clear['Informacje dodatkowe'].str.get_dummies(sep=', ').add_prefix('dodatkowe_')], 1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  """Entry point for launching an IPython kernel.

In [136]:
df_clear

,Cena,Powierzchnia,Liczba pokoi,Rynek,Materiał budynku,Title_len,numer_pietra,liczba_pieter,Forma własności_pełna własność,Forma własności_spółdzielcze wł. z KW,...,Okna_brak informacji,Okna_drewniane,Okna_plastikowe,Winda_nie,Winda_tak,dodatkowe_brak informacji,dodatkowe_dwupoziomowe,dodatkowe_oddzielna kuchnia,dodatkowe_piwnica,dodatkowe_pom. użytkowe
0,1900000.0,100.00,4.0,0,cegła,23,2.0,6.0,1,0,...,0,0,0,0,1,1,0,0,0,0
1,435000.0,46.00,2.0,0,cegła,46,2.0,3.0,1,0,...,0,0,1,1,0,0,0,1,1,0
2,531962.0,38.00,2.0,0,cegła,49,3.0,3.0,1,0,...,0,0,1,1,0,0,0,1,1,0
3,429000.0,36.00,2.0,0,wielka płyta,31,8.0,10.0,0,1,...,0,0,1,0,1,0,0,1,1,0
4,514000.0,37.24,2.0,0,wielka płyta,48,4.0,10.0,1,0,...,0,0,1,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24169,1479400.0,113.80,4.0,0,wielka płyta,31,10.0,10.0,1,0,...,1,0,0,0,1,0,0,1,1,0
24170,1250000.0,102.00,4.0,0,cegła,48,3.0,4.0,0,1,...,1,0,0,1,0,1,0,0,0,0
24171,419000.0,111.00,5.0,1,brak informacji,50,1.0,3.0,1,0,...,1,0,0,1,0,1,0,0,0,0
24173,429000.0,94.79,4.0,1,cegła,50,0.0,0.0,1,0,...,0,0,1,1,0,1,0,0,0,0
24179,419000.0,111.00,5.0,1,cegła,50,1.0,2.0,1,0,...,0,0,1,1,0,0,1,0,0,1

In [137]:
df_clear['Materiał budynku'].value_counts()

brak informacji    8818
cegła              5305
inne               1523
wielka płyta       1242
żelbet              493
pustak              471
silikat             365
beton komórkowy     210
beton               108
Name: Materiał budynku, dtype: int64

In [138]:
df_clear = pd.get_dummies(df_clear, columns=['Materiał budynku'])

In [139]:
df_clear

,Cena,Powierzchnia,Liczba pokoi,Rynek,Title_len,numer_pietra,liczba_pieter,Forma własności_pełna własność,Forma własności_spółdzielcze wł. z KW,Forma własności_spółdzielcze własnościowe,...,dodatkowe_pom. użytkowe,Materiał budynku_beton,Materiał budynku_beton komórkowy,Materiał budynku_brak informacji,Materiał budynku_cegła,Materiał budynku_inne,Materiał budynku_pustak,Materiał budynku_silikat,Materiał budynku_wielka płyta,Materiał budynku_żelbet
0,1900000.0,100.00,4.0,0,23,2.0,6.0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
1,435000.0,46.00,2.0,0,46,2.0,3.0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
2,531962.0,38.00,2.0,0,49,3.0,3.0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
3,429000.0,36.00,2.0,0,31,8.0,10.0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,514000.0,37.24,2.0,0,48,4.0,10.0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24169,1479400.0,113.80,4.0,0,31,10.0,10.0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
24170,1250000.0,102.00,4.0,0,48,3.0,4.0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
24171,419000.0,111.00,5.0,1,50,1.0,3.0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
24173,429000.0,94.79,4.0,1,50,0.0,0.0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
24179,419000.0,111.00,5.0,1,50,1.0,2.0,1,0,0,...,1,0,0,0,1,0,0,0,0,0

In [140]:
# Check is there any nan value in dataframe
df_clear.isna().sum()

Cena                                           0
Powierzchnia                                   0
Liczba pokoi                                   0
Rynek                                          0
Title_len                                      0
numer_pietra                                   0
liczba_pieter                                  0
Forma własności_pełna własność                 0
Forma własności_spółdzielcze wł. z KW          0
Forma własności_spółdzielcze własnościowe      0
Forma własności_udział                         0
Stan wykończenia_brak informacji               0
Stan wykończenia_do remontu                    0
Stan wykończenia_do wykończenia                0
Stan wykończenia_do zamieszkania               0
balkon_balkon                                  0
balkon_brak informacji                         0
balkon_ogródek                                 0
balkon_taras                                   0
Miejsce parkingowe_brak                        0
Miejsce parkingowe_garaż/miejsce parkingowe    0
Ogrzewanie_brak informacji                     0
Ogrzewanie_elektryczne                         0
Ogrzewanie_gazowe                              0
Ogrzewanie_inne                                0
Ogrzewanie_kotłownia                           0
Ogrzewanie_miejskie                            0
Rodzaj zabudowy_apartamentowiec                0
Rodzaj zabudowy_blok                           0
Rodzaj zabudowy_brak informacji                0
Rodzaj zabudowy_dom wolnostojący               0
Rodzaj zabudowy_kamienica                      0
Rodzaj zabudowy_szeregowiec                    0
Okna_aluminiowe                                0
Okna_brak informacji                           0
Okna_drewniane                                 0
Okna_plastikowe                                0
Winda_nie                                      0
Winda_tak                                      0
dodatkowe_brak informacji                      0
dodatkowe_dwupoziomowe                         0
dodatkowe_oddzielna kuchnia                    0
dodatkowe_piwnica                              0
dodatkowe_pom. użytkowe                        0
Materiał budynku_beton                         0
Materiał budynku_beton komórkowy               0
Materiał budynku_brak informacji               0
Materiał budynku_cegła                         0
Materiał budynku_inne                          0
Materiał budynku_pustak                        0
Materiał budynku_silikat                       0
Materiał budynku_wielka płyta                  0
Materiał budynku_żelbet                        0
dtype: int64

In [141]:
# Check data type
df_clear.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18535 entries, 0 to 24179
Data columns (total 53 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Cena                                         18535 non-null  float64
 1   Powierzchnia                                 18535 non-null  float64
 2   Liczba pokoi                                 18535 non-null  float64
 3   Rynek                                        18535 non-null  int64
 4   Title_len                                    18535 non-null  int64
 5   numer_pietra                                 18535 non-null  float64
 6   liczba_pieter                                18535 non-null  float64
 7   Forma własności_pełna własność               18535 non-null  uint8
 8   Forma własności_spółdzielcze wł. z KW        18535 non-null  uint8
 9   Forma własności_spółdzielcze własnościowe    18535 non-null  uint8
 10  Forma własności_udział                       18535 non-null  uint8
 11  Stan wykończenia_brak informacji             18535 non-null  uint8
 12  Stan wykończenia_do remontu                  18535 non-null  uint8
 13  Stan wykończenia_do wykończenia              18535 non-null  uint8
 14  Stan wykończenia_do zamieszkania             18535 non-null  uint8
 15  balkon_balkon                                18535 non-null  int64
 16  balkon_brak informacji                       18535 non-null  int64
 17  balkon_ogródek                               18535 non-null  int64
 18  balkon_taras                                 18535 non-null  int64
 19  Miejsce parkingowe_brak                      18535 non-null  uint8
 20  Miejsce parkingowe_garaż/miejsce parkingowe  18535 non-null  uint8
 21  Ogrzewanie_brak informacji                   18535 non-null  uint8
 22  Ogrzewanie_elektryczne                       18535 non-null  uint8
 23  Ogrzewanie_gazowe                            18535 non-null  uint8
 24  Ogrzewanie_inne                              18535 non-null  uint8
 25  Ogrzewanie_kotłownia                         18535 non-null  uint8
 26  Ogrzewanie_miejskie                          18535 non-null  uint8
 27  Rodzaj zabudowy_apartamentowiec              18535 non-null  uint8
 28  Rodzaj zabudowy_blok                         18535 non-null  uint8
 29  Rodzaj zabudowy_brak informacji              18535 non-null  uint8
 30  Rodzaj zabudowy_dom wolnostojący             18535 non-null  uint8
 31  Rodzaj zabudowy_kamienica                    18535 non-null  uint8
 32  Rodzaj zabudowy_szeregowiec                  18535 non-null  uint8
 33  Okna_aluminiowe                              18535 non-null  uint8
 34  Okna_brak informacji                         18535 non-null  uint8
 35  Okna_drewniane                               18535 non-null  uint8
 36  Okna_plastikowe                              18535 non-null  uint8
 37  Winda_nie                                    18535 non-null  uint8
 38  Winda_tak                                    18535 non-null  uint8
 39  dodatkowe_brak informacji                    18535 non-null  int64
 40  dodatkowe_dwupoziomowe                       18535 non-null  int64
 41  dodatkowe_oddzielna kuchnia                  18535 non-null  int64
 42  dodatkowe_piwnica                            18535 non-null  int64
 43  dodatkowe_pom. użytkowe                      18535 non-null  int64
 44  Materiał budynku_beton                       18535 non-null  uint8
 45  Materiał budynku_beton komórkowy             18535 non-null  uint8
 46  Materiał budynku_brak informacji             18535 non-null  uint8
 47  Materiał budynku_cegła                       18535 non-null  uint8
 48  Materiał budynku_inne                        18535 non-null  uint8
 49  Materiał budynku_pustak                      18535 non-null  uint8
 50  Materiał budynku_silikat                     18535 non-null  uint8
 51  Materiał budynku_wielka płyta                18535 non-null  uint8
 52  Materiał budynku_żelbet                      18535 non-null  uint8
dtypes: float64(5), int64(11), uint8(37)
memory usage: 3.1 MB

In [142]:
# Save data into dataframe

In [144]:
df_clear.to_csv(r'/content/drive/MyDrive/OTO_DOM_REGRESSION/numericML_data.csv', sep = ';')